[package]
name = "mathion"
version = "0.1.0"
authors = ["ANEP-Research <quickwshell@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2"
lazy_static = "1"